CLASS zbp_cs_cds_unm_log_v2_test DEFINITION  PUBLIC FINAL CREATE PUBLIC FOR TESTING.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.
CLASS zbp_cs_cds_unm_log_v2_test  IMPLEMENTATION.
ENDCLASS.
