CLASS zsu_es_cds_unm_log_test DEFINITION  PUBLIC FINAL CREATE PUBLIC FOR TESTING.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.
CLASS zsu_es_cds_unm_log_test  IMPLEMENTATION.
ENDCLASS.
