CLASS zsu_es_cds_unm_log_test_single DEFINITION  PUBLIC FINAL CREATE PUBLIC FOR TESTING.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.
CLASS zsu_es_cds_unm_log_test_single  IMPLEMENTATION.
ENDCLASS.
